language: objective-c

before_script:
    - brew update

script:
   - xcodebuild clean build -sdk iphonesimulator -workspace ShowMovies.xcworkspace -scheme ShowMovies CODE_SIGNING_REQUIRED=NO

branches:
  only:
    - master
